### ISSUE TITLE
[Vtwo Mini] Changing batteries, resetting stats and confirming "old coil" causes firing at 30W

### ISSUE THREAD

**Issue by forkoz** [maelstrom2001/ArcticFox#59]
I'm running the 1/16 release on my vtwo mini and using a 1.4 ohm coil with SS316L. When I change batteries, reset stats and keep the old coil the mod fires at 30W instead of the 10 it was set to. I have to go into toolbox and re-upload the profile for it to stop. If I select "new" coil it gives a TCR error and will not fire.

from: https://github.com/TBXin/NFirmwareEditor/issues/130

It keeps firing at 30W while I hold down the button, huge vapor and burnt smell. Resistance at rest is 1.43ohms  I disabled TCR check so you are right that it comes from there.

Last night I remember the same thing happening and my coils was 1.25.

**Comment by maelstrom2001** [comment]
> disabled TCR check

Did I understand you correctly - the problem was solved?

**Comment by forkoz** [comment]
"solved" as in I turn off TCR check. Otherwise it keeps firing at 30W even if you lower the temperature. I will try a 1.1 ohm next.

**Comment by forkoz** [comment]
At 1.04 ohms the device fires very quickly at 30w and then stops. So if you build a coil technically <1.5ohms but its hot or the resistance changes the TCR check will fire indefinitely and cook things.

**Comment by TBXin** [comment]
This is a default behavior for any firmware. As maelstrom2001 says - you can disable TCR Check and device will never try to check coil with a 30 watts warmup.

**Comment by forkoz** [comment]
IMO, it should still fail or stop after 1s to match the 1 ohm behavior. There must be something goofed for it to just keep firing. What's worse is that the logger doesn't appear to record that the 30w firing is happening.

**Comment by maelstrom2001** [comment]
> it should still fail or stop after 1s

It is not acceptable for complex builds. Too few time to warm up, for example, fused claptons, and it constantly will rise TCR Errors. And I didn't mention any strange things like notch coils...
Summing up: you know what coil you install to atomizer, but box can only guess what exactly it is.

**Comment by forkoz** [comment]
I don't know what it is checking exactly. Resistance rise? I set TFR and material manually and don't have smart mode on. There is only VW profile and this one for SS316L

**Comment by TBXin** [comment]
You can't select any material while your profile in the VW mode, so, your porifle in the Temp. Control mode and thats why box is checking resistanse rise.

**Comment by forkoz** [comment]
It did it even when puling the battery in the temp profile. Are you saying if I disable VW, leaving one profile, it will stop?

**Comment by TBXin** [comment]
em... Battery temp profile... WAT?

![](http://i.imgur.com/NsUUgQ0.png)

That's all you should do to get rid of 30 watts starting boost.

**Comment by forkoz** [comment]
you misunderstand, this happens when I pull the battery out resetting the device while the current profile is TC. I was asking if the TCR check was caused by having a VW and TC profile registered in the device.

**Comment by TBXin** [comment]
TCR check appropriate only for TC mode. If your active profile in the VW mode - you will never get TCR checks and TCR errors.

**Comment by maelstrom2001** [comment]
> 1/16 release

What is it? Update to [170103](https://github.com/maelstrom2001/ArcticFox/releases/tag/170103)

**Comment by forkoz** [comment]
I'm at 170116. Forgot that you write D/M/Y and I write M/D/Y. 1/16 is January 16th. If I only use VW of course I get no TCR check, same if I turn it off. Not saying there is no work around.

But TCR check should not continuously fire 30w towards the top end of the resistance range especially when everything is set up in the profile and on top of that write 10w in the device monitor. Not everyone is sub ohming at the highest power possible.

**Comment by maelstrom2001** [comment]
> same if I turn it off

I. e., when you turn Check TCR off everything is OK, and box will start from right power value?

**Comment by forkoz** [comment]
basically. I turned off TCR check completely so I wouldn't get a 30W surprise vaping in TC mode and changing batteries.
